/* THE COLLECTION.
   One object per ticket, in any order — the page sorts by date.
   Six invented tickets ship with the kit so it runs the moment you
   open it. Replace this file with your own; see docs/DATA.md for
   what every field is for and which ones the page actually reads. */
window.TICKETS = [
{
"id": 1,
"title_raw": "JURASSIC PARK",
"title": "Jurassic Park",
"date": "1993-06-11",
"year": 1993,
"showtime": "7:15pm",
"theater": "The Roxy",
"format": [],
"price": "$6.50",
"seat": "Auditorium 3",
"confidence": "high",
"notes": "Sample stub — not a real ticket.",
"file": "t001.jpg",
"source": "sample (drawn, not scanned)",
"page": 1,
"w": 760,
"h": 1120,
"theater_short": "The Roxy",
"aud": "Aud 3"
},
{
"id": 2,
"title_raw": "MATRIX, THE",
"title": "The Matrix",
"date": "1999-03-31",
"year": 1999,
"showtime": "9:40pm",
"theater": "Grand Cinema 8",
"format": [],
"price": "$7.75",
"seat": "Auditorium 7",
"confidence": "high",
"notes": "Sample stub. Title printed with the article moved to the end.",
"file": "t002.jpg",
"source": "sample (drawn, not scanned)",
"page": 2,
"w": 760,
"h": 1120,
"theater_short": "Grand Cinema 8",
"aud": "Aud 7"
},
{
"id": 3,
"title_raw": "SPIRITED AWAY",
"title": "Spirited Away",
"date": "2002-09-20",
"year": 2002,
"showtime": "4:30pm",
"theater": "Palace Twin",
"format": [],
"price": "$5.00",
"seat": "Screen 1",
"confidence": "high",
"notes": "Sample stub — a matinee, so this night opens in daylight.",
"file": "t003.jpg",
"source": "sample (drawn, not scanned)",
"page": 3,
"w": 760,
"h": 1120,
"theater_short": "Palace Twin",
"aud": "Aud 1"
},
{
"id": 4,
"title_raw": "LOTR FELLOWSHIP",
"title": "The Lord of the Rings: The Fellowship of the Ring",
"date": "2001-12-19",
"year": 2001,
"showtime": "12:01am",
"theater": "Grand Cinema 8",
"format": [],
"price": "$8.00",
"seat": "Auditorium 1",
"confidence": "high",
"notes": "Sample stub — a midnight show, the darkest sky the room has.",
"file": "t004.jpg",
"source": "sample (drawn, not scanned)",
"page": 4,
"w": 760,
"h": 1120,
"theater_short": "Grand Cinema 8",
"aud": "Aud 1"
},
{
"id": 5,
"title_raw": "CASABLANCA 1942",
"title": "Casablanca",
"date": "2004-02-14",
"year": 2004,
"showtime": "2:00pm",
"theater": "The Roxy",
"format": [],
"price": "$5.50",
"seat": "Auditorium 2",
"confidence": "high",
"notes": "Sample stub — a revival screening of a 1942 film.",
"file": "t005.jpg",
"source": "sample (drawn, not scanned)",
"page": 5,
"w": 760,
"h": 1120,
"theater_short": "The Roxy",
"aud": "Aud 2"
},
{
"id": 6,
"title_raw": "BLADE RUNNER FC",
"title": "Blade Runner",
"date": "2007-10-05",
"year": 2007,
"showtime": "10:20pm",
"theater": "Starlite Drive-In",
"format": [],
"price": "$9.00",
"seat": "Screen 2",
"confidence": "high",
"notes": "Sample stub — a drive-in, so the seat is a screen.",
"file": "t006.jpg",
"source": "sample (drawn, not scanned)",
"page": 6,
"w": 760,
"h": 1120,
"theater_short": "Starlite Drive-In",
"aud": "Screen 2"
}
];
